# Generated by Django 6.1 on 2026-08-18 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Име на играта')),
                ('subject', models.CharField(max_length=100, verbose_name='Дисциплина/Тема')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('center_image', models.ImageField(blank=True, null=True, upload_to='game_images/', verbose_name='Централна картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL, verbose_name='Създател')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игри',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция (номер на квадратчето)')),
                ('field_type', models.CharField(choices=[('START', 'Старт'), ('QUESTION', 'Въпрос'), ('BONUS', 'Бонус'), ('PENALTY', 'Наказание'), ('FINISH', 'Финал'), ('INFO', 'Информация')], default='QUESTION', max_length=20, verbose_name='Тип на поле')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Етикет (име на полето)')),
                ('material_title', models.CharField(blank=True, max_length=200, verbose_name='Заглавие на материала')),
                ('material_content', models.TextField(blank=True, verbose_name='Съдържание на материала')),
                ('material_image', models.ImageField(blank=True, null=True, upload_to='field_materials/', verbose_name='Картинка към материала')),
                ('material_link', models.URLField(blank=True, verbose_name='Връзка към допълнителен материал')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main_app.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Полета',
                'ordering': ['position'],
            },
        ),
    ]
