# Generated by Django 6.1 on 2026-08-18 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('LEARN', 'Запознаване с материал'), ('PRACTICE', 'Затвърждаване'), ('EXAM', 'Изпит')], default='LEARN', max_length=10, verbose_name='Режим на игра'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на групата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='main_app.game', verbose_name='Активна игра')),
                ('students', models.ManyToManyField(related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='Студенти')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to=settings.AUTH_USER_MODEL, verbose_name='Преподавател')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main_app.game')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст на въпроса')),
                ('question_type', models.CharField(choices=[('MC', 'Множествен избор (4 отговора)'), ('OPEN', 'Отворен отговор')], default='MC', max_length=10, verbose_name='Тип въпрос')),
                ('option1', models.CharField(blank=True, max_length=255, verbose_name='Отговор 1')),
                ('option2', models.CharField(blank=True, max_length=255, verbose_name='Отговор 2')),
                ('option3', models.CharField(blank=True, max_length=255, verbose_name='Отговор 3')),
                ('option4', models.CharField(blank=True, max_length=255, verbose_name='Отговор 4')),
                ('correct_options', models.CharField(blank=True, help_text='Номера на верните отговори, разделени със запетая (напр. 1,3)', max_length=10, verbose_name='Верни отговори')),
                ('correct_answer', models.TextField(blank=True, verbose_name='Верен отговор (за отворен въпрос)')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Точки за верен отговор')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Тежест (за изпит)')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main_app.field', verbose_name='Свързано поле')),
            ],
        ),
    ]
