# Generated by Django 6.1 on 2026-09-26 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_group_teacher_group_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_material_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущ материал'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='turn_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ред на хвърляне'),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='main_app.group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Банка',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='FieldOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_price', models.IntegerField(default=100, verbose_name='Цена на покупка')),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='main_app.field', verbose_name='Поле')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_fields', to=settings.AUTH_USER_MODEL, verbose_name='Собственик')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_fields', to='main_app.gamesession', verbose_name='Сесия')),
            ],
            options={
                'verbose_name': 'Собственост',
                'verbose_name_plural': 'Собствености',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Пореден номер')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('content', models.TextField(blank=True, verbose_name='Съдържание')),
                ('formula', models.TextField(blank=True, verbose_name='Формули')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео URL')),
                ('question_text', models.TextField(verbose_name='Текст на въпроса')),
                ('option1', models.CharField(max_length=255, verbose_name='Отговор 1')),
                ('option2', models.CharField(max_length=255, verbose_name='Отговор 2')),
                ('option3', models.CharField(max_length=255, verbose_name='Отговор 3')),
                ('option4', models.CharField(blank=True, max_length=255, verbose_name='Отговор 4')),
                ('correct_options', models.CharField(help_text='Номера на верните отговори, разделени със запетая (напр. 1,3)', max_length=10, verbose_name='Верни отговори')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main_app.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материали',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField(verbose_name='Номер на хода')),
                ('dice_value', models.PositiveIntegerField(verbose_name='Стойност на зара')),
                ('from_position', models.PositiveIntegerField(verbose_name='От позиция')),
                ('to_position', models.PositiveIntegerField(verbose_name='До позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.material', verbose_name='Материал')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='main_app.gamesession', verbose_name='Сесия')),
            ],
            options={
                'verbose_name': 'Ход',
                'verbose_name_plural': 'Ходове',
                'ordering': ['turn_number'],
            },
        ),
    ]
